# Generated by Django 2.2.9 on 2020-02-25 10:36

from django.db import migrations, models
import galerie.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0002_image_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('statut', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=galerie.models.image_path)),
            ],
        ),
        migrations.DeleteModel(
            name='Galerie',
        ),
        migrations.DeleteModel(
            name='Image_Long',
        ),
    ]
