# Generated by Django 2.2.9 on 2020-02-26 16:55

from django.db import migrations
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesion',
            name='numero_de_telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='pays',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
