# Generated by Django 2.2.9 on 2020-02-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titrologie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revue',
            options={'ordering': ['-id']},
        ),
    ]
